export const API_REQUEST = 'API Request:';
export const URL_AUTH = '/metaserver/api/v1/auth-service';
export const URL_USER = '/metaserver/api/v1/user-service';
export const URL_POST = '/metaserver/api/v1/post-service';
export const ACT_MESSAGE = 'Message';
export const ACT_BLOCK = 'Block';
export const ACT_UNBLOCK = 'Unblock';
export const ACT_UNFRIEND = 'Unfriend';
export const ACT_POST = 'Post'
export const ACT_COMMENT = 'Comment'
export const ACT_ADD_FRIEND = 'Add Friend'
export const ACT_ACCEPT_REQUEST = 'Accept Request'
export const ACT_DELETE_REQUEST = 'Delete Request'
export const ACT_LIKE = 'Like'
export const GET_POST_DEFAULT_OFFSET=0
export const GET_POST_DEFAULT_LIMIT=10
export const GET_COMMENT_DEFAULT_OFFSET=0
export const GET_COMMENT_DEFAULT_LIMIT=10
export const GET_FR_DEFAULT_OFFSET=0
export const GET_FR_DEFAULT_LIMIT=10
export const GET_LIKE_DEFAULT_OFFSET=0
export const GET_LIKE_DEFAULT_LIMIT=10